/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoardBoardIdRouteImport } from './routes/board.$boardId'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as IssueIssueKeyIdeRouteImport } from './routes/issue.$issueKey.ide'
import { Route as IssueIssueKeyChatRouteImport } from './routes/issue.$issueKey.chat'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardBoardIdRoute = BoardBoardIdRouteImport.update({
  id: '/board/$boardId',
  path: '/board/$boardId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const IssueIssueKeyIdeRoute = IssueIssueKeyIdeRouteImport.update({
  id: '/issue/$issueKey/ide',
  path: '/issue/$issueKey/ide',
  getParentRoute: () => rootRouteImport,
} as any)
const IssueIssueKeyChatRoute = IssueIssueKeyChatRouteImport.update({
  id: '/issue/$issueKey/chat',
  path: '/issue/$issueKey/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/board/$boardId': typeof BoardBoardIdRoute
  '/issue/$issueKey/chat': typeof IssueIssueKeyChatRoute
  '/issue/$issueKey/ide': typeof IssueIssueKeyIdeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/board/$boardId': typeof BoardBoardIdRoute
  '/issue/$issueKey/chat': typeof IssueIssueKeyChatRoute
  '/issue/$issueKey/ide': typeof IssueIssueKeyIdeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/board/$boardId': typeof BoardBoardIdRoute
  '/issue/$issueKey/chat': typeof IssueIssueKeyChatRoute
  '/issue/$issueKey/ide': typeof IssueIssueKeyIdeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/search'
    | '/settings'
    | '/auth/callback'
    | '/board/$boardId'
    | '/issue/$issueKey/chat'
    | '/issue/$issueKey/ide'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/search'
    | '/settings'
    | '/auth/callback'
    | '/board/$boardId'
    | '/issue/$issueKey/chat'
    | '/issue/$issueKey/ide'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/search'
    | '/settings'
    | '/auth/callback'
    | '/board/$boardId'
    | '/issue/$issueKey/chat'
    | '/issue/$issueKey/ide'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  BoardBoardIdRoute: typeof BoardBoardIdRoute
  IssueIssueKeyChatRoute: typeof IssueIssueKeyChatRoute
  IssueIssueKeyIdeRoute: typeof IssueIssueKeyIdeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board/$boardId': {
      id: '/board/$boardId'
      path: '/board/$boardId'
      fullPath: '/board/$boardId'
      preLoaderRoute: typeof BoardBoardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issue/$issueKey/ide': {
      id: '/issue/$issueKey/ide'
      path: '/issue/$issueKey/ide'
      fullPath: '/issue/$issueKey/ide'
      preLoaderRoute: typeof IssueIssueKeyIdeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issue/$issueKey/chat': {
      id: '/issue/$issueKey/chat'
      path: '/issue/$issueKey/chat'
      fullPath: '/issue/$issueKey/chat'
      preLoaderRoute: typeof IssueIssueKeyChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  BoardBoardIdRoute: BoardBoardIdRoute,
  IssueIssueKeyChatRoute: IssueIssueKeyChatRoute,
  IssueIssueKeyIdeRoute: IssueIssueKeyIdeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
