/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoardBoardIdRouteImport } from './routes/board.$boardId'
import { Route as IssueIssueKeyIdeRouteImport } from './routes/issue.$issueKey.ide'
import { Route as IssueIssueKeyChatRouteImport } from './routes/issue.$issueKey.chat'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardBoardIdRoute = BoardBoardIdRouteImport.update({
  id: '/board/$boardId',
  path: '/board/$boardId',
  getParentRoute: () => rootRouteImport,
} as any)
const IssueIssueKeyIdeRoute = IssueIssueKeyIdeRouteImport.update({
  id: '/issue/$issueKey/ide',
  path: '/issue/$issueKey/ide',
  getParentRoute: () => rootRouteImport,
} as any)
const IssueIssueKeyChatRoute = IssueIssueKeyChatRouteImport.update({
  id: '/issue/$issueKey/chat',
  path: '/issue/$issueKey/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/board/$boardId': typeof BoardBoardIdRoute
  '/issue/$issueKey/chat': typeof IssueIssueKeyChatRoute
  '/issue/$issueKey/ide': typeof IssueIssueKeyIdeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/board/$boardId': typeof BoardBoardIdRoute
  '/issue/$issueKey/chat': typeof IssueIssueKeyChatRoute
  '/issue/$issueKey/ide': typeof IssueIssueKeyIdeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/board/$boardId': typeof BoardBoardIdRoute
  '/issue/$issueKey/chat': typeof IssueIssueKeyChatRoute
  '/issue/$issueKey/ide': typeof IssueIssueKeyIdeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/board/$boardId'
    | '/issue/$issueKey/chat'
    | '/issue/$issueKey/ide'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/board/$boardId'
    | '/issue/$issueKey/chat'
    | '/issue/$issueKey/ide'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/board/$boardId'
    | '/issue/$issueKey/chat'
    | '/issue/$issueKey/ide'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  BoardBoardIdRoute: typeof BoardBoardIdRoute
  IssueIssueKeyChatRoute: typeof IssueIssueKeyChatRoute
  IssueIssueKeyIdeRoute: typeof IssueIssueKeyIdeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board/$boardId': {
      id: '/board/$boardId'
      path: '/board/$boardId'
      fullPath: '/board/$boardId'
      preLoaderRoute: typeof BoardBoardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issue/$issueKey/ide': {
      id: '/issue/$issueKey/ide'
      path: '/issue/$issueKey/ide'
      fullPath: '/issue/$issueKey/ide'
      preLoaderRoute: typeof IssueIssueKeyIdeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issue/$issueKey/chat': {
      id: '/issue/$issueKey/chat'
      path: '/issue/$issueKey/chat'
      fullPath: '/issue/$issueKey/chat'
      preLoaderRoute: typeof IssueIssueKeyChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  BoardBoardIdRoute: BoardBoardIdRoute,
  IssueIssueKeyChatRoute: IssueIssueKeyChatRoute,
  IssueIssueKeyIdeRoute: IssueIssueKeyIdeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
